In [7]:
import numpy as np
import random

In [147]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

arr1 = np.random.randint(1,100,(3,3))
arr1

array([[70, 52, 74],
       [15, 89, 11],
       [94, 37,  9]])

In [149]:
arr1.T #Interchanged in Rows to Clolumn

array([[70, 15, 94],
       [52, 89, 37],
       [74, 11,  9]])

In [35]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr2.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
arr2.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [84]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

random_array = np.random.rand(4,4)
border_array = np.zeros((6,6))


In [86]:
border_array [1:5 , 1:5] = random_array

print("Random 4x4 Array:")
print(random_array)
print("\n6x6 Array with a Border of Zeros:")
print(border_array)

Random 4x4 Array:
[[0.39300471 0.96263529 0.56034015 0.49545518]
 [0.28868257 0.06061811 0.42214254 0.29740884]
 [0.16627907 0.02088736 0.35869012 0.82567971]
 [0.34648002 0.9027956  0.71555739 0.47525009]]

6x6 Array with a Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.39300471 0.96263529 0.56034015 0.49545518 0.        ]
 [0.         0.28868257 0.06061811 0.42214254 0.29740884 0.        ]
 [0.         0.16627907 0.02088736 0.35869012 0.82567971 0.        ]
 [0.         0.34648002 0.9027956  0.71555739 0.47525009 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [225]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
array = np.arange(10,61,5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [94]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
#(uppercase, lowercase, title case, etc.) to each element.

String = "python", "numpy", "pandas"
np.array(String)

# Uppercase
upper_case = np.char.upper(String)

#Lowercase
lower_case = np.char.lower(String)

#Titlecase
title_case = np.char.title(String)

print("Uppercase:")
print(upper_case)
print("\nLowercase:")
print(lower_case)
print("\nTitlecase:")
print(lower_case)

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Titlecase:
['python' 'numpy' 'pandas']


In [98]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
word_array = np.array(["Hello","Welcome","to","India"])

spaced_words_array = np.array([' '.join(word) for word in word_array])

print("Word Array:")
print(word_array)
print ("\nSpaced Words:")
print(spaced_words_array)

Word Array:
['Hello' 'Welcome' 'to' 'India']

Spaced Words:
['H e l l o' 'W e l c o m e' 't o' 'I n d i a']


In [105]:
#  7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

Array1 = np.array([[80,95],[74,67]])
Array1


array([[80, 95],
       [74, 67]])

In [107]:
Array2 = np.array([[50,45],[24,15]])
Array2

array([[50, 45],
       [24, 15]])

In [119]:
Addition = Array1 + Array2
Substraction = Array1 - Array2
Multiplication = Array1 * Array2
Division = Array1 / Array2

print("Addition Result:")
print(Addition)

print("\nSubstraction Result:")
print(Substraction)

print("\nMultiplication Result:")
print(Multiplication)

print("\nDivision Result:")
print(Division)

Addition Result:
[[130 140]
 [ 98  82]]

Substraction Result:
[[30 50]
 [50 52]]

Multiplication Result:
[[4000 4275]
 [1776 1005]]

Division Result:
[[1.6        2.11111111]
 [3.08333333 4.46666667]]


In [117]:
#  8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
Identity_matrix = np.eye(5, dtype=int)
Identity_matrix
Diagnol_elements = np.diag(Identity_matrix)

print("5x5 Identity Mattrix:")
print(Identity_matrix)

print("\nDiagnol elements:")
print(Diagnol_elements)
      

5x5 Identity Mattrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Diagnol elements:
[1 1 1 1 1]


In [123]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

Random_integers = np.random.randint(0,1000,100)
Random_integers

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

Prime_numbers = [num for num in Random_integers if is_prime(num)]

print("Random Array:")
print(Random_integers)

print("\nPrime Numbers:")
print(Prime_numbers)

Random Array:
[489 328 601 963 815 350 639 616 427 478 274 480 442 802 708  68 691 181
 248 693 600 127 848 532  78 963 139 358 987 537 666 313 857 541 910 313
 506 743 672 444 957 180 205 312 173 798 533 530 779 665 590 376  25 706
 616 542 645 226 496 571 533 618 153 630 185  30 606 484 649 597  33 197
 584 743 651 477 499 549 868 975 481 259 255 307 373  74 686 306 372 183
 898 818  83 365  92 590 896 178 985 792]

Prime Numbers:
[601, 691, 181, 127, 139, 313, 857, 541, 313, 743, 173, 571, 197, 743, 499, 307, 373, 83]


In [125]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

daily_temperatures = np.random.randint(20, 40, size=30)  # Random temperatures between 20 and 40 degrees

# Reshape the array into 4 weeks (each week has 7 days, except the last one with 9 days for a 30-day month)
weeks = np.split(daily_temperatures[:28], 4)  # First 4 full weeks
last_week = daily_temperatures[28:]           # Last week (2 remaining days)

# Weekly average for first 4 weeks
weekly_averages = [np.mean(week) for week in weeks]
weekly_averages.append(np.mean(last_week))  # Average for the last week


print("Daily Temperatures for the Month:\n") 
print(daily_temperatures)

print("\nWeekly Averages:\n")
print(weekly_averages)


Daily Temperatures for the Month:

[30 38 38 36 29 23 22 21 37 31 22 20 23 24 34 29 32 24 39 27 23 31 21 24
 34 32 21 30 31 35]

Weekly Averages:

[30.857142857142858, 25.428571428571427, 29.714285714285715, 27.571428571428573, 33.0]
